apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-ml-api
  labels:
    app: mini-ml-api
spec:
  replicas: {{ .Values.api.replicas | default 1 }}
  selector:
    matchLabels:
      app: mini-ml-api
  template:
    metadata:
      labels:
        app: mini-ml-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.registry }}-api:{{ .Values.image.api_tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: 8000
          resources:
            {{- toYaml (.Values.api.resources | default dict) | nindent 12 }}
