{{- if .Values.inference.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mini-ml-inference
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mini-ml-inference
  minReplicas: {{ .Values.inference.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.inference.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.inference.hpa.targetCPUUtilizationPercentage | default 60 }}
{{- end }}
