name: ci-cd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      OWNER_LC: ${{ github.repository_owner | lower }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # (опционально) автолейблы/таги по коммиту/ветке
      - name: Docker meta (API)
        id: meta_api
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/mini-ml-api
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./services/api
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}

      - name: Docker meta (Inference)
        id: meta_inf
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/mini-ml-inference
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Build & push Inference
        uses: docker/build-push-action@v6
        with:
          context: ./services/inference
          push: true
          tags: ${{ steps.meta_inf.outputs.tags }}
          labels: ${{ steps.meta_inf.outputs.labels }}
