name: ci-cd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./services/api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mini-ml-api:latest

      - name: Build & push Inference
        uses: docker/build-push-action@v6
        with:
          context: ./services/inference
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mini-ml-inference:latest